name: RegEx Issue Labeler
on:
  issues:
    types: [opened, edited]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
